### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by snmslavk** [hallem/RestSharpMaintainers#7]
I guess that it's not an appropriate way to offer my help as here a lot of issues are still unanswered. But if you need help I'd like to help :)

**Comment by hallem** [comment]
It is but life gets in the way.  What I'd like to do is start with triage and investigation. If you're still interested, let me know and I'll add you as a contributor so you can assign issues and PR's that you're looking into and when you ok them, they'll get merged or resolved. After a bit I'll give you write access, and then the ability to publish to nuget.

**Comment by snmslavk** [comment]
I'm still interested

**Comment by hallem** [comment]
i added you as a contributor with read access. please go through the PR's and issues and start triaging.  when you take one please assign it to yourself
